#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update -y
sudo apt-get install nginx -y 
sudo apt-get install ufw -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Holberton School" > /var/www/html/index.html'
sudo service nginx restart
